version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
